language: php

sudo: false

matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env: COLLECT_COVERAGE=true
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.2
      env: STATIC_ANALYSIS=true
    - php: hhvm
      dist: trusty

install:
  - if [[ "$STATIC_ANALYSIS" == "true" ]]; then composer require --dev phpunit/phpunit:^6.3 phpstan/phpstan phpstan/phpstan-phpunit phpstan/phpstan-strict-rules; fi
  - travis_retry composer install --no-interaction --prefer-source

script:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover; fi
  - if [[ "$STATIC_ANALYSIS" != "true" ]]; then vendor/bin/phpunit --no-coverage; fi
  - if [[ "$STATIC_ANALYSIS" == "true" ]]; then vendor/bin/phpstan analyse -c phpstan.neon -l 3 src test; fi

after_script:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
